development:
  cloud_name: dsvuxomzl
  api_key: '328128327848448'
  api_secret: IMlSuqb1XkQTc2xLax_BDXUSnjc
  enhance_image_tag: true
  static_image_support: false

production:
  cloud_name: <%= ENV['CLOUDINARY_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
